@startuml Note object
class Note{
+ modifyPitch(Function<Pitch, Pitch>): Note
+ modifyPosition(Function<Float, Float>): Note
+ modifyDuration(Function<Float, Float>): Note
+ modifyVolume(Function<Float, Float>): Note
+ pitch(): Pitch
+ position(): float
+ duration(): float
+ volume(): float
}
@enduml
